[profile.release]
panic = 'unwind'

[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
    'node',
    'parachain',
    'runtime/*',
    'pallets/*',
    'primitives'
]
exclude = ['rpc']
