[profile.release]
panic = 'unwind'

[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
    'node',
    'parachain',
    'runtime/*',
    'modules/*',
    'pallets/assets',
    'pallets/bridge',
    'pallets/impact-actions',
    'pallets/vesting',
    'primitives'
]
exclude = ['rpc']
